# apps/tribe-front/nginx.conf
server {
    listen 80;
    
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        # CRUCIAL: Se não achar o arquivo, manda pro index.html pro Vue Router assumir
        try_files $uri $uri/ /index.html;
    }
}
