services:
  tribe-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 9Jhx6UU|*@4u4*7N~@6dnYLZ/TeR[acy[Z"
      MYSQL_DATABASE: tribe_db
      MYSQL_USER: tribe_user
      MYSQL_PASSWORD: siT&3p4;4,\7<.IbF=r0wMwVML<Y0>~s&Ps
    volumes:
      - mysql_data:/var/lib/mysql

  tribe-api:
    build: 
      context: ./apps/tribe-api # O Docker "entra" nesta pasta para buildar
    container_name: tribe-api
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=tribe-db # O Nest deve usar o nome do serviço como Host
      - DATABASE_USER=root
      - DATABASE_PASSWORD=9Jhx6UU|*@4u4*7N~@6dnYLZ/TeR[acy[Z"
    depends_on:
      - tribe-db

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "80:80"