worker_processes auto;
events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    
    server {
        listen 80;

        location /api/ {
            # 1. CORS Preflight
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE, PATCH' always;
                add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization' always;
                add_header 'Access-Control-Max-Age' 1728000;
                return 204;
            }

            # 2. O PULO DO GATO: Remova a barra após o 3000.
            # Sem a barra, o Nginx repassa a URL INTEIRA (/api/auth/login) para o Nest.
            proxy_pass http://tribe-api:3000; 

            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # 3. Headers de resposta para o Navegador
            add_header 'Access-Control-Allow-Origin' '*' always;
        }

        location / {
            # Aqui a barra final é necessária pois queremos que o "/" 
            # do IP aponte para a raiz do container do front.
            proxy_pass http://tribe-front:80/; 
            proxy_set_header Host $host;
        }
    }
}