# ./nginx.conf (na raiz do monorepo)
worker_processes auto;
events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    
    server {
        listen 80;

        location /api/ {
            # Tratamento de Preflight (OPTIONS)
            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' '*';
                add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS, PUT, DELETE, PATCH';
                add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization';
                add_header 'Access-Control-Max-Age' 1728000;
                add_header 'Content-Type' 'text/plain; charset=utf-8';
                add_header 'Content-Length' 0;
                return 204;
            }

            proxy_pass http://tribe-api:3000/; # Removi o /api/ extra se seu Nest já não tiver prefixo global
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Headers de CORS para as respostas reais
            add_header 'Access-Control-Allow-Origin' '*' always;
        }

        location / {
            proxy_pass http://tribe-front:80/;
            proxy_set_header Host $host;
        }
    }
}